<section>
    <h1>Connexion</h1>
    <p id="loginStatus" class="requestSent"></p>
    <form id="loginForm" action="admin-office.php" method="POST">
        <fieldset id="loginFieldset">
            <table>
                <tbody>
                    <tr>
                        <td>
                            <label for="login">Identifiant : </label>
                            <input class="admin" type="text" name="login" id="login" placeholder="Identifiant" required>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="password">Mot de passe : </label>
                            <input class="admin" type="password" name="password" id="password" placeholder="Mot de passe" required>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="button" name="button" id="loginBtn" value="Envoyer">
                        </td>
                    </tr>
                </tbody>
            </table>
        </fieldset>
    </form>
</section>