 <p id="loginStatus" class="requestSent"></p>
        <form id="loginForm" action="admin-office.php" method="POST">
            <fieldset id="loginFieldset">
                <table>
                    <tbody>
                        <tr>
                            <td>
                                <label for="login" required>Identifiant : </label>
                                <input class="admin" type="text" name="login" id="login" placeholder="Identifiant">
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label for="password" required>Mot de passe : </label>
                                <input class="admin" type="password" name="password" id="password"
                                       placeholder="Mot de passe">
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="button" name="button" id="loginBtn" value="Envoyer">
                            </td>
                        </tr>
                    </tbody>
                </table>
            </fieldset>
        </form>
