<table id="rdvCal">
    <tbody>
    <!--LA PREMIERE RANGÉE INCLUS LES INFOS DES JOURS DE LA SEMAINE AFFICHÉE ENTOURÉS DES BOUTONS PREVIOUS ET NEXT -->
        <tr>
            <!--LE BOUTON PREVIOUS CHARGE LA PAGE EN FONCTION DES GET PRESENTS DANS L'URL-->
            <td rowspan="12" class="weekBtn">
                <a href="prendre-rdv.php?week=<?= $calendar->previousWeek()->week; ?>&month=<?= $calendar->previousWeek()->month; ?>&year=<?= $calendar->previousWeek()->year; ?>#rdvSect"
                    <?php
                    //SI LE LUNDI AFFICHÉ EST INFÉRIEUR À AUJOURD'HUI OU SI ON EST UN JOUR DE WEEK-END ET QUE LE LUNDI AFFICHÉ EST LE LUNDI QUI VIENT APRÈS AUJOURD'HUI OU SI ON EST UNE SEMAINE ANTÉRIEUR À CELLE D'AUJOURD'HUI, ALORS ON AJOUTE L'ID UNAVPREVIOUSWEEK POUR QU'IL NE SOIT PAS POSSIBLE DE CLIQUER DESSUS//
                    if($calendar->getDayToString(1) <= $calendar->getDayToday() || ($calendar->sundayCheck()==true && $calendar->mondayCheck()==true) || $calendar->previousWeek()->week < date('W')): ?>
                        id="unavPreviousWeek"
                    <?php
                    //SINON L'ID EST PREVIOUSWEEK,ON PEUT CLIQUER DESSUS//
                    else: ?>
                        id="previousWeek"
                    <?php endif; ?>>4</a>
                <?php ; ?>
                </td>

            <?php
            //ON CRÉE LES CASES DES JOURS DE LA SEMAINE, DU LUNDI AU SAMEDI DONC 5 CASES//
            for ($day = 1; $day <= 6; $day++): ?>
            <td class ='calendarDate'>
                <!--ON RÉCUPÈRE LES NOMS NUMEROS ET MOIS ET ON LES AFFICHE-->
                <span class='bold block'> <?= $calendar->getDayNameCal($day); ?> </span>
                <span class='block'><?= $calendar->getDayNumber($day); ?> </span> <?= $calendar->getMonthNameCal($day); ?>
            </td>
            <?php endfor ?>
            <!--LE BOUTON PREVIOUS CHARGE LA PAGE EN FONCTION DES GET PRESENTS DANS L'URL-->
            <td rowspan="12" class="weekBtn">
                <a href="prendre-rdv.php?week=<?= $calendar->nextWeek()->week; ?>&month=<?= $calendar->nextWeek()->month; ?>&year=<?= $calendar->nextWeek()->year; ?>#rdvSect" <?php
                //SI LA SEMAINE SUIVANTE EST SUPÉRIEURE OU ÉGALE À 12 SEMAINE APRÈS CELLE D'AUJOURD'HUI, ON AJOUTE L'ID UNAVNEXTWEEK POUR QU'IL NE SOIT PAS POSSIBLE DE CLIQUER DESSUS//
                if($calendar->nextWeek()->week >= (date('W') + 12) ): ?>
                    id="unavNextWeek"
                <?php
                //SINON L'ID EST NEXTWEEK,ON PEUT CLIQUER DESSUS//
                else: ?>
                    id="nextWeek"
                <?php endif; ?>>5</a>
            </td>
        </tr>
            <?php
                //ON CRÉE LES LIGNES DU TABLEAU PAR CRÉNEAU HORAIRE, DE 8H30 À 20H//

                for ($timeSlot=0; $timeSlot < count($calendar->timeSlots); $timeSlot++): ?>
        <tr>
                        <?php
                        //PUIS ON CRÉE LES CASES PAR JOUR, DU LUNDI AU SAMEDI//
                        for ($day=1; $day<=6;$day++): ?>
            <td>
                <input type="button"
                       id="<?= $calendar->getTimeSlotId($day).' '.$calendar->timeSlots[$timeSlot];
                       //ON CRÉE L'ID AU FORMAT "Y-m-d H:i:s"//?>:00"
                    <?php
                    //SI LE CRENEAU EXISTE DANS LES TABLES 'RDV' OU 'UNAVAILABLE' OU SI LE JOUR EST ANTÉRIEUR À LA AUJOURD'HUI OU SI LA SEMAINE SUIVANTE EST SUPÉRIEURE OU ÉGALE À 12 SEMAINE APRÈS CELLE D'AUJOURD'HUI OU SI L'ANNÉE EST DIFFÉRENTE DE L'ANNÉE ACTUELLE, ALORS ON AJOUTE LA CLASSE UNAVTIME POUR RENDRE LE CRÉNEAU NON CLIQUABLE//
                    if (isset ($weekRdvs[$calendar->getTimeSlotId($day).' '.$calendar->timeSlots[$timeSlot].":00"]) || $calendar->getTimeSlotId($day) <= $calendar->getDayToday() || (rdvClass::getTimeSlotAvailability($calendar->getTimeSlotId($day).' '.$calendar->timeSlots[$timeSlot].":00")!= false) || $calendar->nextWeek()->week > (date('W') + 12) || $calendar->nextWeek()->year != date('Y')): ?>
                        class="unavTime timeSlot"
                    <?php
                    //SINON ON AJOUTE LA CLASSE AVTIME,ON PEUT CLIQUER DESSUS//
                    else :?>
                        class="avTime timeSlot"
                    <?php endif; ?>
                       name="<?= $calendar->getDayName($day); ?> <?= $calendar->getDayNumber($day); ?> <?= $calendar->getMonthName($day); ?> <?= $calendar->getYear($day); ?> <?= $calendar->timeSlots[$timeSlot]; //LE NAME CORRESPOND À LA DATE COMPLETE EX: LUNDI 09 MARS 2020//?>" value="<?= $calendar->timeSlots[$timeSlot]; ?>">

            </td>
                        <?php endfor; ?>
        </tr>
                <?php endfor; ?>
    </tbody>
</table>


