<section id="contactSect">
  <h1>Contact</h1>
  <h2>Poser une question, solliciter un devis ou demander un RDV</h2>
  <p class="requestSent"></p>
  <form id="contactForm" action="contact.php" method="POST">
    <fieldset>
      <table id="contactInputs">
        <tbody>
          <tr>
            <td>
              <label for="contactFirstName">Votre prénom <span class="red">*</span> : </label>
              <input class="userInfo firstName" type="text" name="contactFirstName" id="contactFirstName" placeholder="Prénom" required>
            </td>
            <td>
              <label for="contactLastName">Votre nom <span class="red">*</span> : </label>
              <input class="userInfo lastName" type="text" name="contactLastName" id="contactLastName" placeholder="Nom" required>
            </td>
          </tr>
          <tr>
            <td>
              <label for="contactPhone">Votre téléphone <span class="red">*</span> : </label>
              <input class="userInfo phone" type="text" name="contactPhone" id="contactPhone" placeholder="Téléphone" required>
            </td>
            <td>
              <label for="contactEmail">Votre email <span class="red">*</span> : </label>
              <input class="userInfo email" type="text" name="contactEmail" id="contactEmail" placeholder="Email" required>
            </td>
          </tr>
          <tr>
            <td colspan="2">
              <label for="contactMessage">Votre message <span class="red">*</span> : </label>
              <textarea class="message" id="contactMessage" name="contactMessage" rows="8" cols="80" maxlength="2000" required></textarea>
            </td>
          </tr>
          <tr>
            <td colspan="2">
              <input type="button" name="button" id="contactBtn" value="Envoyer">
              <p>Les champs indiqués par une <span class="red">*</span> sont obligatoires.</p>
            </td>
          </tr>
        </tbody>
      </table>
    </fieldset>
  </form>
</section>
<script src="js/active.js"></script>