<section id="douleur" class="specialisations">
    <h1>Gestion de la Douleur</h1>
    <img src="img/brown-and-white-bear-plush-toy-round-small.png" alt="photo_ours_en_peluche_blessé_avec_bangages_et_pansements" id="imgDouleur">
    <h2>Je vous accompagne sur la gestion de la douleur, aigüe ou chronique.</h2>
    <div class="alertWindowBgArt">
        <div class="alertWindowArt">
            <div class='alertWindowContentArt'>
            </div>
            <button type="button" class="alertBtnArt" name="alertBtnArt"><i class="fas fa-times" style="margin-right: 0"></i></button>
        </div>
    </div>
    <div id="accompDouleur">
        <p>Quand on souffre, quand on a mal, quelle que soit l’origine de cette douleur, notre vie est bouleversée, on ne pense plus qu’à cela, nous devenons notre douleur… C’est assez infernal.</p>
        <p> La sophrologie est reconnue comme une technique efficace dans la gestion quotidienne de la douleur. Elle permet d’apporter, si ce n’est une diminution notable de la douleur, une nette amélioration du confort de vie. </p>
    </div>
    <article>
        <h2>QU’EST-CE QUE LA DOULEUR ?</h2>
        <p>La douleur est définie officiellement par l’association internationale pour l’étude de la douleur (IASP) : <span class="italic">"la douleur est une expérience sensorielle et émotionnelle désagréable associée à une lésion tissulaire réelle ou potentielle ou décrite dans ces termes"</span> .</p>
        <p>Il ressort de cette définition que la douleur est un ressenti personnel. <span class="bold blue">La douleur est une perception, elle est toujours vraie, ressentie et très différente d’une personne à l’autre</span>. Elle peut être niée ou mal comprise, parce qu’elle est souvent invisible, et tellement difficile à appréhender. Il est important de pouvoir partager sa douleur, parce que vous n’êtes pas seul.e.</p>
        <p>Les années 2000 marquent le début d’une prise en charge sérieuse de la douleur, jusqu’ici assez niée par la médecine ou prise en charge par des traitements médicamenteux uniquement. Fort heureusement, les mécanismes de la douleur font désormais l’objet de nombreuses recherches scientifiques, et il est désormais reconnu que les techniques non médicamenteuses, dont la sophrologie, l’hypnose, la relaxation, s’avèrent efficaces dans la gestion de la douleur.</p>
        <p>La gestion de la douleur est devenue <span class="bold blue">un enjeu majeur de santé publique</span> inscrit dans la loi de santé publique de 2004. Le soulagement de la douleur est même devenu depuis 2002 un droit fondamental pour toute personne.</p>
    </article>
    <article>
        <h2>LE PARCOURS D’UNE INFORMATION DOULOUREUSE (douleur aiguë)</h2>
        <p>Exemple : brûlure de la main :</p>
        <img src="img/parcours-d-une-information-douloureuse.png" class="clickable" alt="schema-du-parcours-de-l'information-douloureuse">
    </article>
    <article>
        <h2>LES DIFFERENTES FORMES DE DOULEUR</h2>
        <p>· La douleur aiguë : intense et brève (- de 3 mois), liée à une blessure ou un traumatisme.</p>
        <p>· La douleur chronique : durée variant de 3 à 6 mois, la douleur est installée, c’est une maladie à part entière. Cette dernière a de lourdes conséquences sur la vie : physiologiques, psychologiques, affectives, émotionnelles voire anatomiques. A la différence de la douleur aiguë, les tissus restent endommagés, le cerveau continue de produire de la douleur. Elle n’est pas systématiquement liée à une lésion, ce qui la rend difficile à étudier et à appréhender. Elle s’accompagne fréquemment de composantes cognitives, sentiment d’injustice, de culpabilité, de stress intense, et même de dépression.</p>
    </article>
    <article>
        <h2>LA SOPHROLOGIE ET LA DOULEUR</h2>
        <p>La sophrologie est particulièrement efficace dans la gestion de la douleur chronique. </p>
        <p>Les exercices de sophrologie, adaptés à chaque personne, vous permettront d’abord une acceptation (partielle ou totale) de la douleur, son repositionnement dans le corps (retrouver un espace dans son corps qui n’est pas douloureux), une observation différente sur cette douleur, etc. </p>
        <p>L’objectif est de retrouver un confort de vie, en dépolarisant l’attention de la douleur chronique afin de repasser dans l’action. </p>
        <p>Pour cela, la sophrologie permet de rétablir un bon état émotionnel, le cerveau peut alors atténuer la douleur et très progressivement, se reprogrammer. </p>
    </article>
    <article>
        <h2>AXES DE TRAVAIL EN SOPHROLOGIE</h2>
        <p>Diverses techniques sont proposées en sophrologie et principalement :</p>
        <h3>La Défocalisation</h3>
        <p>Il s’agit de déplacer l’attention de la zone douloureuse vers un autre endroit non douloureux. La personne s’ouvre alors à d’autres perceptions, et l’écoute portée vers la zone douloureuse est moindre. Dans le cas de la douleur chronique, cette technique permet de ne plus se percevoir uniquement comme un corps douloureux.</p>
        <p>La réaction est neurophysiologique : l’endorphine (morphine produite par le corps lors de la séance de sophrologie) va inhiber la libération de la substance douloureuse (neurotransmetteur, substance P) vers le cerveau. C’est une bonne technique de régulation de la douleur. </p>
        <p>Cette technique est utilisée par les pompiers lors d’accidents graves, pour les douleurs aiguës.</p>
        <h3>La Focalisation</h3>
        <p>Il s’agit, à l’inverse de la technique précédente, de porter l’attention sur la zone douloureuse en vue de la transformer. Oser faire face à la douleur permet de dépasser la peur de celle-ci, et d’effacer les tensions inutiles. La personne apprend à regarder la douleur, reprend le contrôle de celle-ci.</p>
        <p>Fortement utilisée pour la douleur chronique, cette technique permet physiologiquement, en plus de la précédente, d’éteindre la sensation douloureuse en substituant une autre sensation. Il est en effet impossible d’avoir deux sensations qui passent en même temps (une douloureuse, une agréable) par le même canal de transmission en direction du cerveau. La sensation agréable est substituée à la sensation douloureuse.</p>
        <h3>La Réinterprétation</h3>
        <p>La douleur a une composante cognitive. Cette technique permet de poser des mots sur la douleur, lui donner du sens, réfléchir à ses causes, à son apparition, etc.</p>
        <p>Il apparaît utile de mettre des mots sur la souffrance qui se tait afin de lui donner un autre sens.</p>
        <p>Ce sujet me parle personnellement car je suis handicapée physique depuis plusieurs années, après un accident de sport. La sophrologie m’a permis d’accéder à un quotidien moins douloureux, dans tous les sens du terme. </p>
    </article>
    <article id="plusLoinDouleur">
        <h2>Pour aller plus loin</h2>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/9qJuARzD9d4" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <ul>
            <li><a href="https://www.inserm.fr/information-en-sante/dossiers-information/douleur" target="_blank">INSERM : La Douleur</a></li>
            <li><a href="https://www.e-cancer.fr/Patients-et-proches/Qualite-de-vie/Douleur/La-douleur-c-est-quoi" target="_blank">E-cancer.fr : La Douleur, c'est quoi ?</a></li>
            <li><a href="https://solidarites-sante.gouv.fr/IMG/pdf/la_douleur_en_questions.pdf" target="_blank">Solidarites-sante.gouv : La Douleur en Questions</a></li>
        </ul>
    </article>
    <ul class="btnsList" id="indexBtns">
        <li><a href="contact.php">Me contacter</a></li>
        <li><a href="prendre-rdv.php">Prendre rendez-vous</a></li>
    </ul>
    <small>La sophrologue intervient en soutien, elle ne pose pas de diagnostic. <br><span class="blue bold">Il est recommandé avant toute intervention du sophrologue d’avoir l’avis d’un.e médecin généraliste ou spécialiste</span>.</small>
</section>
<script src="js/active.js"></script>