<section id="homePage">
    
    <h1 class="mainTitle">Célia Rouby - Sophrologue <br><span class="regularFont black">vous accueille dans son cabinet</span> <br> <a href="https://www.google.com/maps/place/1+Cours+de+la+R%C3%A9publique,+69100+Villeurbanne/@45.7716454,4.8738017,17z/data=!3m1!4b1!4m5!3m4!1s0x47f4c028206d9c09:0xe058699fb308e8f9!8m2!3d45.7716454!4d4.8738017" target="_blank" id="cabMap"><span class="regularFont bold">1 cours de la République 69100 Villeurbanne</span></a></h1>
    <ul id="covidList">
        <li class="italic">Masque obligatoire dans le cadre du respect des règles sanitaires.</li>
        <li class="italic">Je vous propose également des séances en <a href="contact.php">télé-consultation</a>.</li>
    </ul>
    <p><a href="infos-pratiques.php">Visite à domicile possible</a></p>

    
    <article class="homePage" id="topArticle">
        <a href="infos-pratiques.php">
            <ul id="indexList">
                <li><h3>Accompagnement sur mesure en fonction de vos besoins</h3></li>
                <li>Adultes - Adolescent.e.s</li>
                <li><h3>Séances individuelles et collectives</h3></li>
                <li id="speAnchor">Structures médicales / associatives - Entreprises</li>
            </ul>
        </a>
    </article>
    <article id="specialisations">
        <ul>
            <li id="liViolences">
                <a href="violences.php">
                    <img src="img/adult-alone-autumn-brick-round-small.png" alt="photo_adulte_déprimé" id="imgViolencesAccueil">
                    <h3>Violences, traumatismes & État de stress post-traumatique</h3></a>
            </li>
            <li id="liCorps">
                <a href="rapport-au-corps.php">
                    <img src="img/mirror-with-condensation-round-small.png" alt="photo_silhouette_dans_miroir_embué" id="imgCorpsAccueil">
                    <h3>Rapport au corps, Féminité</h3>
                </a>
            </li>
            <li id="liDouleur">
                <a href="gestion-de-la-douleur.php">
                    <img src="img/brown-and-white-bear-plush-toy-round-small.png" alt="photo_ours_en_peluche_blessé_avec_bangages_et_pansements" id="imgDouleurAccueil">
                    <h3>Gestion de la douleur</h3>
                </a>
            </li>
        </ul>
    </article>
    <ul class="btnsList" id="indexBtns">
        <li><a href="contact.php">Me contacter</a></li>
        <li><a href="prendre-rdv.php">Prendre rendez-vous</a></li>
    </ul>
    <ul id="syndic">
        <li>Membre de la Chambre syndicale de la sophrologie</li>
        <li><a href="https://www.chambre-syndicale-sophrologie.fr" target="_blank"><img src="img/logo-CSS-basse-def.jpg" alt="logo-Chambre-Syndicale-de-la-Sophrologie"></a></li>
    </ul>
    <small class="italic">La sophrologie est une technique de support qui <span class="bold blue">ne se substitue en aucun cas à un avis et/ou traitement médical</span>. Seul le médecin est habilité à diagnostiquer et prescrire.</small>
</section>
<script type="text/javascript" src="js/active.js"></script>