<section id="homePage">
    <h1 class="mainTitle">Célia Rouby - Sophrologue <br> Lyon 3ème</h1>
    <article class="homePage" id="topArticle">
        <a href="infos-pratiques.php">
            <ul id="indexList">
                <li><h3>Accompagnement sur mesure en fonction de vos besoins</h3></li>
                <li>Adultes - Adolescent.e.s</li>
                <li><h3>Séances individuelles et collectives</h3></li>
                <li id="speAnchor">Structures médicales / associatives - Entreprises</li>
            </ul>
        </a>
    </article>
    <article id="specialisations">
        <ul>
            <li id="liViolences">
                <a href="violences.php">
                    <img src="img/adult-alone-autumn-brick-round-small.png" alt="photo_adulte_déprimé" id="imgViolencesAccueil">
                    <h3>Violences, traumatismes & État de stress post-traumatique</h3></a>
            </li>
            <li id="liCorps">
                <a href="rapport_au_corps.php">
                    <img src="img/mirror-with-condensation-round-small.png" alt="photo_silhouette_dans_miroir_embué" id="imgCorpsAccueil">
                    <h3>Rapport au corps, Féminité</h3>
                </a>
            </li>
            <li id="liDouleur">
                <a href="gestion_de_la_douleur.php">
                    <img src="img/brown-and-white-bear-plush-toy-round-small.png" alt="photo_ours_en_peluche_blessé_avec_bangages_et_pansements" id="imgDouleurAccueil">
                    <h3>Gestion de la douleur</h3>
                </a>
            </li>
        </ul>
    </article>
    <ul class="btnsList" id="indexBtns">
        <li><a href="contact.php">Me contacter</a></li>
        <li><a href="prendre-rdv.php">Prendre rendez-vous</a></li>
    </ul>
    <small class="italic">La sophrologie est une technique de support qui <span class="bold blue">ne se substitue en aucun cas à un avis et/ou traitement médical</span>. Seul le médecin est habilité à diagnostiquer et prescrire.</small>
</section>
<script type="text/javascript" src="js/active.js"></script>