<section id="ipPage">
  <h1 class="mainTitle">Infos Pratiques</h1>
  <article id="tarifs">
    <h2>LES TARIFS</h2>
      <ul>
          <li>Séance individuelle au cabinet : <span class="bold blue"> 60 €</span></li>
          <li>Séance individuelle adolescent.e.s : <span class="bold blue"> 45 €</span></li>
          <li>Séance individuelle à domicile : <span class="bold blue"> 70 €</span></li>
          <li>Séance de groupe : <span class="bold blue"> sur devis (5 participants minimum)</span></li>
      </ul>
      <div>
          <p>Séances en entreprise, écoles, etc : <a href="contact.php">sur devis</a>.</p>
      </div>
      <h3>Paiements</h3>
      <p>Moyens de paiement acceptés : <span class="bold"> espèces, chèques</span>.</p>
      <p>Les séances ne sont pas remboursées par la sécurité sociale, mais <span class="bold blue">peuvent être prises en charge par certaines
              mutuelles</span>.</p>
      <p> Renseignez-vous auprès de votre mutuelle.</p>
  </article>
  <article id="seances">
    <h2>LES SÉANCES</h2>
      <article>
          <h3>Durée d'un accompagnement</h3>
          <ul>
              <li>L'accompagnement individuel en sophrologie varie <span class="bold blue">entre 5 et 10 séances</span>, selon votre
                  objectif.
              </li>
              <li>Les séances sont <span class="bold blue">accessibles à tou·te·s.</span></li>
              <li>La sophrologie se pratique assise et/ou debout.</li>
              <li>Il n’est pas exigé de tenue vestimentaire particulière.</li>
          </ul>
      </article>
      <article>
          <h3>Durée d'une séance</h3>
          <ul>
              <li>Séances individuelles : <span class="bold blue">1h</span></li>
              <li>Première séance individuelle : <span class="bold blue">1h30 environ</span></li>
              <li>Séances collectives : <span class="bold blue">1h30</span></li>
          </ul>
      </article>
  </article>
  <article id="cabinet">
    <h2>LE CABINET</h2>
      <h3>Plan d'accès</h3>
    <p>1 cours de la République 69100 Villeurbanne</p>
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2782.9772898537826!2d4.871613015706285!3d45.77164537910585!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47f4c028206d9c09%3A0xe058699fb308e8f9!2s1%20Cours%20de%20la%20R%C3%A9publique%2C%2069100%20Villeurbanne!5e0!3m2!1sfr!2sfr!4v1591946695662!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
  </article>
    <ul id="ipBtns" class="btnsList">
        <li><a href="contact.php">Me contacter</a></li>
        <li><a href="prendre-rdv.php">Prendre rendez-vous</a></li>
    </ul>
</section>
<script type="text/javascript" src="js/active.js"></script>