<section id="ipPage">
  <h1 class="mainTitle">Infos Pratiques</h1>
  <article id="tarifs">
    <h2>LES TARIFS</h2>
      <ul>
          <li>Séance individuelle : <span class="bold blue"> 60 €</span></li>
          <li>Séance de groupe : <span class="bold blue"> sur devis (selon le nombre de paticipants)</span></li>
      </ul>
      <div>
          <p>Séances en entreprise, écoles, etc : <a href="contact.php">sur devis</a>.</p>
      </div>
      <h3>Paiements</h3>
      <p>Moyens de paiement acceptés : <span class="bold"> espèces, chèques</span>.</p>
      <p>Les séances ne sont pas remboursées par la sécurité sociale, mais <span class="bold blue">peuvent être prises en charge par certaines
              mutuelles</span>.</p>
      <p> Renseignez-vous auprès de votre mutuelle.</p>
  </article>
  <article id="seances">
    <h2>LES SÉANCES</h2>
      <article>
          <h3>Durée d'un accompagnement</h3>
          <ul>
              <li>L'accompagnement individuel en sophrologie varie <span class="bold blue">entre 8 et 12 séances</span>, selon votre
                  objectif.
              </li>
              <li>Les séances sont <span class="bold blue">accessibles à tou·te·s.</span></li>
              <li>La sophrologie se pratique assis·e et/ou debout.</li>
              <li>Il n’est pas exigé de tenue vestimentaire particulière.</li>
          </ul>
      </article>
      <article>
          <h3>Durée d'une séance</h3>
          <ul>
              <li>Séances individuelles : <span class="bold blue">1h</span></li>
              <li>Première séance individuelle : <span class="bold blue">1h30 environ</span></li>
              <li>Séances collectives : <span class="bold blue">1h30</span></li>
          </ul>
      </article>
  </article>
    <ul id="ipBtns" class="btnsList">
        <li><a href="contact.php">Me contacter</a></li>
        <li><a href="prendre-rdv.php">Prendre rendez-vous</a></li>
    </ul>
</section>
<script type="text/javascript" src="js/active.js"></script>