<section id="sophroSect">
    <section id="sophroTopArt">
      <h1 class="mainTitle">La Sophrologie</h1>
      <h4>La sophrologie est une <span class="bold blue">méthode psycho-corporelle</span> dont l’usage peut être thérapeutique ou de développement personnel.<br>Par le biais de techniques simples et répétées, vous développez vos propres ressources et renforcez vos capacités corporelles et psychiques !</h4>
      <article id="sophroTopArtPart01">
          <ul>
              <li>Elle a été créée dans les années 60 par le neuropsychiatre colombien Alphonso Caycédo, après de <span class="bold blue">multiples
              influences occidentales et orientales</span> (yoga, hypnose, etc).
              </li>
              <li><span class="bold blue">Sa démarche est scientifique</span> : il s’est penché sur les différents états de la conscience
                  et
                  considère l’individu dans sa globalité, comme une unité corporelle et mentale.
              </li>
              <li>Le but de cette pratique est de parvenir à <span class="bold blue">la consolidation d’un équilibre « global »</span>,
                  une
                  harmonie entre le corps et le mental.
              </li>
          </ul>
      </article>
      <article id="sophroTopArtPart02">
          <ul>
              <li>La sophrologie induit <span class="bold blue">un état de conscience propice à la détente et à l’apprentissage de nouveaux
              comportements</span>.
              </li>

              <li>Le principe est de <span class="bold blue">revenir aux sensations, aux ressentis corporels</span>. Cela permet
                  simplement de
                  reposer, calmer
                  le mental, les pensées, images, émotions qui nous traversent tout au long de la journée.
              </li>
          </ul>
      </article>
        <article id="sophroPractice">
            <ul>
                <li>Par des <span class="bold blue">pratiques simples</span>, alliant des respirations, des décontractions
                musculaires et/ou des visualisations,
                la sophrologie amène la personne à mettre de côté les mauvais réflexes ou certaines attitudes
                automatiques
                conditionnées par l’environnement (société, sphère familiale, professionnelle, etc), notamment grâce
                à la
                découverte de soi :

                    <ul id="sophroPracticeSubList">
                        <li>
                            Meilleure perception du <span class="bold blue">corps</span>.
                        </li>
                        <li>
                            Meilleure gestion des <span class="bold blue">pensées</span>.
                        </li>
                        <li>
                            Meilleure connaissance et gestion des <span class="bold blue">émotions</span>.
                        </li>
                        <li>
                            Meilleure conscience des <span class="bold blue">valeurs personnelles</span>.
                        </li>
                    </ul>
                </li>
            </ul>
        </article>
    </section>
    <article id="sophroMidArt">
        <h2>Une Méthode Accessible à Tout le Monde !</h2>
        <p>Les exercices sont adaptés <span class="bold blue">en fonction des
              capacités de chacun.e</span>. </p>
        <p>Elle ne requiert aucune aptitude physique ou intellectuelle particulière !</p>
    </article>
    <section id="sophroSectPart02">
        <article>
            <article id="sophroBottomArt">
                <h2>L’Entraînement</h2>
                <ul>
                    <li>La sophrologie s’appuie sur un <span class="bold blue">entraînement personnel indispensable</span>.</li>
                    <li>La répétition régulière des pratiques enseignées est tout à fait essentielle.</li>
                    <li>C’est cette répétition qui permet de modifier les comportements (comme dans un domaine sportif ou artistique !).</li>
                    <li><span class="bold blue">L’entrainement personnel ne demande que très peu de temps</span> (quelques secondes peuvent suffire) et il se pratique
                        partout (dans les transports, au travail, et même sous la douche).</li>
                </ul>
            </article>
        </article>
        <article id="sophroSectPart02Img">
            <img src="img/person-raising-her-hands-3621954.jpg" alt="photo-femme-qui-s'étire"><br>
        </article>
    </section>
    <ul class="btnsList" id="sophroBtns">
        <li><a href="contact.php">Me contacter</a></li>
        <li><a href="prendre-rdv.php">Prendre rendez-vous</a></li>
    </ul>
</section>
<script type="text/javascript" src="js/active.js"></script>