<section id="quiSuisJe">
<h1 class="mainTitle">Qui suis-je ?</h1>
<aside id="me">
        <img src="img/photo-celia.jpg" alt="photographie Célia Rouby" id="celiaRoubyPhoto">
        <div id="formations"><h3>Mes formations :</h3>
            <ul>
                <li>2012 : Master 2 - Droit de la Santé Publique.</li>
                <li>2017-2019 : Sophrologie, CEAS PARIS.</li>
                <li>2018-2019 : Diplôme Universitaire en Victimologie, Paris Descartes.</li>
            </ul>
        </div>
    </aside>
    <article id="aboutMe">
        <h3>Sophrologue et juriste spécialisée en santé publique / victimologie</h3>

        <p>J’ai travaillé quelques années dans la fonction publique, en tant que juriste en santé publique, avec des
            expériences parfois satisfaisantes, parfois non.</p>

        <p>Et puis, il y a quelques années, je me suis retrouvée dans une impasse personnelle. Un gros nœud. C’est à ce
            moment-là que j’ai commencé à pratiquer la sophrologie. J’ai ensuite décidé de me former à cette pratique
            pendant deux années, pour apprendre, comprendre, expérimenter, …</p>

        <p>Ce fût une sacrée belle découverte ! En effet, la sophrologie m’accompagne désormais au quotidien, par
            petites touches, en fonction des besoins de l’instant. Les pratiques ne durent parfois que quelques
            secondes, et hop, tout va mieux. Plutôt agréable, non ?</p>

        <p>A l’issue de ma formation, j’ai ressenti l’envie de partager cette expérience et de transmettre une boîte à
            outils à chaque personne qui le souhaite.</p>

        <p>Ma principale préoccupation dans ma pratique est de parvenir à débloquer des situations complexes ou non, des
            préoccupations, qui peuvent rendre la vie difficile parfois, de dénouer les nœuds, les uns après les autres,
            en suivant votre rythme. Je travaille en totale bienveillance, et reste à l’écoute de vos besoins, de vos
            ressentis. L’objectif est de vous accompagner vers l’autonomie.</p>
        <aside id="aboutMeList">
            <p><span class="bold">Je peux vous accompagner spécifiquement</span> (<span class="italic">cette liste est non exhaustive</span>)<span class="bold"> pour : </span></p>
            <ul>
                <li>
                    <span class="bold blue">Le trouble de stress post-traumatique</span> : apprendre à (mieux) vivre suite à un évènement traumatique qu’il soit physique, psychique, sexuel, …
                </li>
                <li>
                    <span class="bold blue">La gestion des douleurs dans le corps</span> :
                    <ul id="douleursUl">
                        <li>en post-traumatique, après un accident de la vie.</li>
                        <li>douleurs dues à une maladie, mieux gérer son traitement, la perception de son corps.</li>
                        <li>durant la grossesse (modification du corps, gestion des douleurs en vue de l’accouchement).</li>
                        <li>règles douloureuses.</li>
                    </ul>
                </li>
                <li>
                    <span class="bold blue">La gestion de l’anxiété (ou mauvais stress) et accompagnement à un sommeil réparateur</span> (en lien avec les deux
                    thématiques précédentes).
                </li>
                <li>
                    <span class="bold blue">Le rapport au corps</span> : réinvestir son espace personnel, apprivoiser son corps, ...
                </li>
            </ul>
        </aside>
        <ul id="quiSuisJeBtns" class="btnsList">
                <li><a href="contact.php">Me contacter</a></li>
                <li><a href="prendre-rdv.php">Prendre rendez-vous</a></li>
            </ul>
    </article>
</section>
<script type="text/javascript" src="js/active.js"></script>