 <section id="bodyRel" class="specialisations">
    <article id="accompBodyRel">
        <h1 class="mainTitle">Rapport au corps, Féminité</h1>
        <img src="img/mirror-with-condensation-round-small.png" alt="photo_silhouette_dans_miroir_embué" id="imgCorps">
           <ul id="bodyRelUl">
               <li><span class="blue bold">· Connaître son corps, l’apprivoiser, le sentir bouger, développer une sorte d’invincibilité, de toute-puissance.</span><br>Parce que l’on parvient à vivre en harmonie avec nos actes, nos émotions, nos envies, etc. Personne ne peut atteindre cet espace, excepté vous-même. C’est un sacré avantage dans la vie !</li>
               <li><span class="blue bold">· Le corps, et plus particulièrement le corps des femmes est souvent méconnu.</span><span ><br>Peu étudié à l’école, les femmes connaissent aujourd’hui assez mal leur corps, leur corps interne, leur utérus. Et, les femmes vivent souvent avec des douleurs qui semblent normalement acceptées, ce qui ne devrait pas être le cas. Que ce soit au moment des cycles menstruels, des règles, de la grossesse, de l’accouchement, du post-accouchement, etc.</span></li>
               <li><span class="blue bold">· Les stéréotypes de l’attente du corps parfait que l’on voit partout déstabilisent nos corps et nos émotions.</span><span ><br> Nombreuses sont celles qui se sentent mal, se dévalorisent, se cachent, n’osent pas. Nombreuses sont celles qui développent des troubles des conduites alimentaires. Votre corps a le droit de vivre et d’exister dans des espaces communs, qu’il soit grand, petit, mince, gros, cicatrisé, abîmé, fripé, handicapé, non genré, ou que sais-je. </span></li>
            </ul>
    </article>
    <article id="speEnd">
        <h2>La sophrologie n’est pas à la recherche d’un « bonheur naïf »</h2>
            <p><span class="blue bold"> Elle permet plutôt d’accéder à la découverte de son corps</span>, des endroits où se logent les émotions vécues. A cet espace intérieur si vaste. Et, il est possible d’accéder à son identité en tant que personne vivante et ainsi vivre son existence en tant que sujet et non plus en tant qu’objet.</p>
            <p>Par la sophrologie, je vous accompagne à <span class="blue bold">réinvestir votre espace corporel, comprendre et développer des outils pour vivre le mieux possible avec et à travers lui</span>. Il s’agit ici de chercher en soi son propre potentiel afin de parvenir à apprivoiser son reflet dans le miroir, le regard d’autrui et s’aimer sincèrement.</p>
    </article>
     <ul class="btnsList" id="indexBtns">
         <li><a href="contact.php">Me contacter</a></li>
         <li><a href="prendre-rdv.php">Prendre rendez-vous</a></li>
     </ul>
</section>
<script type="text/javascript" src="js/active.js"></script>

