<body style="width: 100%; text-align: center; font-family: 'Quicksand', sans-serif; font-size: 1.4rem; line-height: 1.6; margin: 1rem auto;">
    <main>
        <section>
            <!--LE LOGO EST TEMPORAIRE, LE TEMPS DE CHARGER L'OFFICIEL SUR UN SERVEUR-->
            <a href="http://www.celiarouby-sophrologue.fr" id="logo" ><img src="../img/logo-sophro-v03.png" alt="celia-rouby-sophrologue"></a><br>
            <h2 style="font-family: 'Handlee', cursive; font-size: 2rem; font-weight: bold; color: #7ECBD6;">Merci {{ firstName }} {{ lastName }}</h2>
            <p>Votre email a été envoyé avec succès à <a href="mailto:celia.rouby@gmail.com">celia.rouby@gmail.com</a></p>
            <p>Votre message :<br>
                <strong><em>{{ message }}</em></strong></p>
        </section>
    </main>
</body>
