<!DOCTYPE html>
<html lang="fr">

<head>
    <title>Célia Rouby - Sophrologue - Lyon</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://fonts.googleapis.com/css?family=Handlee&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand:400,600&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="css/reset.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="css/style.css" media="screen" />
</head>

<body class="container">
    <img src="img/logo-sophro-v03.png" alt="logo" style="width: 20%; display: block; margin:2rem auto;">
    <h1 style="text-align: center; font-family: 'Quicksand', cursive; font-size: 2rem;">Site en construction, revenez bientôt :)</h1>
</body>

</html>