<section id="violences" class="specialisations">
    <div class="alertWindowBgArt">
        <div class="alertWindowArt">
            <div class='alertWindowContentArt'>
            </div>
            <button type="button" class="alertBtnArt" name="alertBtnArt"><i class="fas fa-times"></i></button>
        </div>
    </div>
    <section id="violencesTopSect">
        <section id="violencesMainContent">
            <h1 class="mainTitle">Violences, traumatismes & État de stress post-traumatique</h1>
            <img src="img/adult-alone-autumn-brick-round-small.png" alt="photo adulte déprimé">
            <article id="accompDouleur" >
                <h4>J’accompagne les personnes victimes de différentes formes de violences et de stress post-traumatique :</h4>
                <ul>
                    <li>· Violences sexuelles</li>
                    <li>· Violences physiques</li>
                    <li>· Violences conjugales, emprises</li>
                    <li>· Accident de voiture, deuil difficile, etc</li>
                </ul>
            </article>
            <article id="violenceEtSophro">
                <h4>L’accompagnement sophrologique permet de :</h4>
                <ul>
                    <li><span class="blue bold">· Diminuer les effets du stress intense :</span> limiter les phases d’angoisse, les flash-back, les réactions sévères de panique (tremblements, palpitations, etc), limiter le sentiment de paralysie, limiter les tensions physiques.</li>
                    <li><span class="blue bold">· Faire face à ses émotions pour aborder le quotidien plus sereinement :</span> parvenir à retrouver doucement des relations sociales normales, éprouver à nouveau des sentiments, sortir de l’isolement.</li>
                    <li><span class="blue bold">· Retrouver une confiance en l’avenir :</span> anticiper positivement le futur, limiter les vécus en mode « automatiques »…</li>
                    <li><span class="blue bold">· Mieux dormir :</span> limiter la survenue de cauchemars, les peurs de s’endormir, etc.</li>
                    <li><span class="blue bold">· Retrouver une meilleure concentration.</span></li>
                </ul>
            </article></section>
        <aside id="enSavoirPlusNav">
            <article id="espnArt">
                <h2>En savoir plus :</h2>
                <ul class="blue">
                    <li id="btnTrauma01" class="enSavoirPlusNav">Qu’est-ce qu’un traumatisme ?</li>
                    <li id="btnTrauma02" class="enSavoirPlusNav">Les conséquences d’un Etat de stress post-traumatique</li>
                    <li id="btnTrauma03" class="enSavoirPlusNav">La sophrologie et l’état de stress post-traumatique</li>
                    <li id="btnTrauma04" class="enSavoirPlusNav">Une prise en charge pluridisciplinaire de l’ESPT</li>
                </ul>
                <a href="contact.php">Me contacter</a>
            </article>
        </aside>
    </section>
    <div id="speDiv"><p class="italic">La sophrologie est basée sur <span class="bold blue">l’autonomie de la personne</span>, qui sera en mesure d’utiliser les techniques autant qu’elle en aura besoin dans le quotidien.</p></div>
    <section id="enSavoirPlus">
        <article class="bulle hide" id="defTrauma">
            <h2>Qu’est-ce qu’un traumatisme ?</h2>

            <p>En France, on considère que l’évènement traumatique est caractérisé par la confrontation d’une personne avec sa propre mort (DSM 4). L’évènement traumatisant est <span class="blue bold">passé</span>.</p>
            <p> <span class="blue bold">Au moment du traumatisme, le corps se met en alerte, une réaction de survie se met en place.</span></p>
            <p>Sur le plan neurophysiologie, l’amygdale est en suractivité, elle produit un court-circuitage des voies nerveuses qui relient le système limbique et le cortex, <span class="blue bold">qui ne peut alors plus moduler la réponse émotionnelle</span>. Cette disjonction physiologique entre le cortex et le cerveau émotionnel peut s’observer par l’imagerie. <span class="blue bold">Très concrètement, cela se traduit par de l’anxiété, une amnésie des faits, le déni, dépersonnalisation ou déréalisation (perte d’attachement, sentiment de détachement, impression d’être isolé.e, etc)</span>. Ce symptôme est assez courant et vraiment difficile à vivre, un sentiment de ne plus être lié à son corps.</p>
            <img src="img/cerveau-espt.png" id="imgCerveau" class="clickable" alt="schéma des altérations cérébrales fonctionnelles et anatomiques liées à l'état de stress post-traumatique chez l'adulte">
            <p><span class="blue bold">Après l’évènement traumatique, un état de stress post-traumatique (ESPT) peut se mettre en place.</span></p>
            <p><span class="blue bold">Cet état de stress se vit dans le quotidien, au présent, alors que l’évènement est passé</span>. Le risque de développer un état de stress post-traumatique varie d’un évènement à l’autre. Par exemple, on note 80% d’ESPT après un viol.</p>
            <p><span class="blue bold">L’ESPT se vit dans le mental, mais aussi dans le corps.</span></p>
        </article>
        <article class="bulle hide" id="consequencesESPT">
            <h2>Les conséquences d’un Etat de stress post-traumatique</h2>

            <p>Directement après l’évènement traumatique, il peut y voir une phase de latence, plus ou moins longue, où il ne se passe pas grand-chose.</p>
            <p>Ensuite, le syndrome de répétition peut apparaitre. Il signifie que la personne revit l’évènement traumatique à intervalles réguliers. Le corps est en alerte permanente.</p>
            <p><span class="blue bold"> Les conséquences du trauma sont multiples et pas toujours conscientes</span> : troubles dissociatifs (pour permettre à la personne de se soustraire à la frayeur qui résulte de l’évènement traumatique), comorbidités : troubles des conduites alimentaires, conduites à risque, addictions, idées noires, etc. </p>
            <p>Cela est vraiment très pénible à vivre pour la personne qui revit régulièrement l’évènement traumatique par des intrusions, des images, des pensées, des sensations corporelles, des cauchemars qui font irruption dans son champ de conscience ou de perception, notamment lorsqu’elle est confrontée à des situations lui rappelant cet évènement. </p>
            <p>La personne évite – souvent sans y parvenir – toutes ces intrusions (n’en parle pas, se tient à l’écart, etc). </p>
            <p>Il n’est pas rare qu’apparaisse une hyper activité neurovégétative (troubles du sommeil, irritabilité, difficultés de concentration, état d’hypervigilance, réactions de sursaut exagérées).</p>
            <p>Ce stress intense perdure dans le temps, continue au présent, alors que l’évènement traumatique est passé. Le corps se souvient, même si le trauma a été oublié.</p>
            <p><span class="blue bold">Les conséquences sur la santé et sur la vie relationnelle sont importantes.</span></p>
            <p>Les traumas peuvent être d’origines multiples, la presse a énormément parlé de l’ESPT lors de la vague des attentats de 2015, qui ont entrainé de nombreux traumatismes chez les personnes directement touchées, mais également indirectement touchées. En dehors des victimes d’attentats, chaque jour, des milliers de personnes sont confrontées à des évènements traumatiques graves : les viols ou tentatives de viols, les agressions sexuelles uniques ou répétées (notamment durant l’enfance), les violences conjugales, les accidents de la route, … la liste est évidemment non exhaustive.</p>
        </article>
        <article class="bulle hide" id="sophroEtESPT">
            <h2>La sophrologie et l’état de stress post-traumatique</h2>
            <p><span class="blue bold">La réaction au traumatisme est physiologique, elle s’inscrit dans le corps</span>. Toutes nos sensations physiques viennent du corps (via les 5 sens), l’anxiété sature les pensées et le corps, les perceptions sont déréglées. C’est la raison pour laquelle les réponses thérapeutiques mises en avant par la recherche scientifique sont, entre autres, les techniques psycho-corporelles.</p>
            <p>Il faut diminuer rapidement le niveau d’anxiété et de peur, afin de pouvoir ensuite travailler sur les sensations physiques et retrouver ses sens, ses perceptions, …</p>
            <h2>L’accompagnement sophrologique</h2>
            <p>La sophrologie permet de réduire divers symptômes du traumatisme.</p>
            <p>La sophrologie intervient sur différents niveaux, le corps, l’esprit, les émotions.</p>
            <h4>La sophrologie peut apporter un apaisement corporel</h4>
            <p>Suite à un traumatisme, il n’est pas rare que le corps soit perçu comme abîmé, douloureux, laissé de côté, impossible à habiter par la personne.</p>
            <p> A travers des exercices très simples, la sophrologie permet de se mettre au contact de ses sensations corporelles, au présent. Les exercices, pratiqués en conscience, apportent une diminution des tensions musculaires. Avec une respiration associée, la personne apprend à renouer petit à petit avec son corps, qui n’apparait plus seulement comme un corps douloureux coincé dans le trauma. Il est alors possible de s’autoriser à percevoir des sensations agréables, le corps peut être vécu comme un espace possible de plaisir, ou de joie.</p>
            <p>Les exercices en sophrologie se font toujours de manière intentionnelle, la conscience est directement dirigée sur les sensations, agréables ou non. Cela modifie le rapport au corps, en sophrologie, on dit que la personne passe de l’OBJET de son corps, à SUJET de son existence. Et ainsi, elle peut agir, vivre, faire des choix en conscience, retrouve une sorte de libre arbitre.</p>
            <h4>La sophrologie peut apporter un apaisement mental</h4>
            <p>L’ESPT s’accompagne en plus du syndrome de répétition, de troubles anxieux. Ainsi, la résurgence d’attaques de panique, de phobies ou d’obsessions peuvent s’ajouter aux autres troubles spécifiques de l’ESPT.</p>
            <p>Lorsque le trouble anxieux apparaît, l’esprit a du mal à rationaliser, canaliser. Les conséquences sont multiples : la personne est l’objet de croyances négatives, de pensées limitantes, d’intrusions permanentes, de ruminations, de difficultés de concentration, etc.</p>
            <p>L’ensemble de ces symptômes ont un retentissement néfaste sur la vie de la personne. Le fonctionnement entier de la personne peut être altéré, et notamment son fonctionnement social ou professionnel.</p>
            <p>La sophrologie agit sur le système nerveux autonome, et aide à rétablir une relation plus apaisée avec son esprit, notamment par l’orientation volontaires des pensées vers des situations apaisantes. En fait, il s’agit de créer des habitudes de fonctionnement qui deviendront peu à peu des réflexes.</p>
            <p>Par ailleurs, avec le travail sophrologique, les émotions sont souvent mieux gérées. Il ne s’agit pas de vivre en coupant ses émotions, il s’agit simplement de pouvoir les percevoir, les identifier, et limiter leurs effets néfastes.</p>
        </article>
        <article class="bulle hide" id="priseEnCharge">
            <h2>Une prise en charge pluridisciplinaire de l’ESPT</h2>
            <p>La meilleure prise en charge de l’ESPT est pluridisciplinaire : médecin psychiatre, gynécologue, psychologue pratiquant une thérapie alternative (EMDR, Hypnose) et thérapie psycho-corporelle (sophrologie notamment).</p>
            <p>La sophrologie ne suffit pas à soigner l’ESPT, elle intervient en complément d’une prise en charge médicale et/ou thérapeutique (en fonction de l’importance des conséquences du traumatisme).</p>
        </article>
    </section>
    <ul class="btnsList" id="indexBtns">
        <li><a href="contact.php">Me contacter</a></li>
        <li><a href="prendre-rdv.php">Prendre rendez-vous</a></li>
        <li><button type="button" id="backToEspn" class="hide btns">Retour au menu</button></li>
    </ul>
</section>
<script type="text/javascript" src="js/active.js"></script>

