<body style="width: 100%; text-align: center; font-family: 'Quicksand', sans-serif; font-size: 1.4rem; line-height: 1.6; margin: 1rem auto;">
    <main>
        <section>
            <!--LE LOGO EST TEMPORAIRE, LE TEMPS DE CHARGER L'OFFICIEL SUR UN SERVEUR-->
            <a href="http://www.celia-rouby-sophrologue.fr" id="logo" ><img src="https://www.designfreelogoonline.com/wp-content/uploads/2015/05/00496-cat-logo-design-free-logomaker-01.png" alt="celia-rouby-sophrologue""></a><br>
            <h2 style="font-size: 2rem; font-weight: bold; color: #7ECBD6;">Merci {{ firstName }} {{ lastName }}</h2>
            <p>Votre email a été envoyé avec succès à <a href="mailto:contact@celia-rouby-sophrologue.fr">contact@celia-rouby-sophrologue.fr</a></p>
            <p>Votre message :<br>
                <strong><em>{{ message }}</em></strong></p>
        </section>
    </main>
</body>
