<body style="width: 90%; text-align: center; font-family: 'Quicksand', sans-serif; font-size: 1.4rem; line-height: 1.6; margin: 1rem auto;">
    <main>
        <section>
            <!--LE LOGO EST TEMPORAIRE, LE TEMPS DE CHARGER L'OFFICIEL SUR UN SERVEUR-->
            <a href="http://www.celia-rouby-sophrologue.fr" id="logo" ><img src="https://www.designfreelogoonline.com/wp-content/uploads/2015/05/00496-cat-logo-design-free-logomaker-01.png" alt="celia-rouby-sophrologue""></a><br>
            <h2 style="font-size: 2rem; font-weight: bold; color: #7ECBD6;">Bonjour {{ firstName }} {{ lastName }} !</h2>
            <h3>Votre rendez-vous avec <strong>Célia Rouby Sophrologue le {{ jour }} à {{ heure }}</strong> a été annulé.</h3>
            <p>Si vous n'êtes pas à l'origine de cette demande ou si vous n'en avez pas été informé.e au préalable, merci de me contacter :<br>
                <a href="tel:06xxxxxxxx">06xxxxxxxx</a><br>
                <a href="mailto:contact@celia-rouby-sophrologue.fr">contact@celia-rouby-sophrologue.fr</a></p>
            <h4>À bientôt!</h4>
        </section>
    </main>
</body>
