<body style="width: 100%; text-align: center; font-family: 'Quicksand', sans-serif; font-size: 1.4rem; line-height: 1.6; margin: 1rem auto;">
    <main>
        <section>
            <!--LE LOGO EST TEMPORAIRE, LE TEMPS DE CHARGER L'OFFICIEL SUR UN SERVEUR-->
            <a href="http://www.celia-rouby-sophrologue.fr" id="logo" ><img src="https://www.designfreelogoonline.com/wp-content/uploads/2015/05/00496-cat-logo-design-free-logomaker-01.png" alt="celia-rouby-sophrologue""></a><br>
            <h2 style="font-size: 2rem; font-weight: bold; color: #7ECBD6;">Nouveau rendez vous :</h2>
            <p>Vous avez rendez-vous avec <strong>{{ firstName }} {{ lastName }}</strong>. <br>
                Motif : <strong>{{ motif }}</strong><br>
                Le <strong>{{ jour }} à {{ heure }}</strong>.</p>
            <p>{{ email }}<br>
                <a href="tel:{{ phone }}">{{ phone }}</a></p>
            <p>{{ preMessage }}<br>
                <strong><em>{{ message }}</em></strong></p>
        </section>
    </main>
</body>
