<body style="width: 100%; text-align: center; font-family: 'Quicksand', sans-serif; font-size: 1.4rem; line-height: 1.6; margin: 1rem auto;">
    <main>
        <section>
            <h2 style="font-family: 'Handlee', cursive; font-size: 2rem; font-weight: bold; color: #7ECBD6;">Merci {{ firstName }} {{ lastName }} !</h2>
            <h3>Votre rendez-vous avec <strong>Célia Rouby Sophrologue</strong> a bien été enregistré.</h3>
            <p><strong>Le {{ jour }} à {{ heure }}</strong>.<br>
                25 rue Charles Richard 69003 Lyon</p>
            <p>Motif : <strong>{{ motif }}</strong></p>
            <p>{{ preMessage }}<br>
                <strong><em>{{ message }}</em></strong></p>
                <a href="http://www.celia-rouby-sophrologue.fr" style="font-family: 'Handlee', cursive;">celiarouby-sophrologue.fr</a><br>
            <p>Pour toutes questions ou annulation, n'hesitez pas à me contacter :<br>
                <a href="tel:+33673851774">06.73.85.17.74</a><br>
                <a href="mailto:celia.rouby@gmail.com">celia.rouby@gmail.com</a></p>
            <h4>À bientôt!</h4>
        </section>
    </main>
</body>

