<body style="width: 90%; text-align: center; font-family: 'Quicksand', sans-serif; font-size: 1.4rem; line-height: 1.6; margin: 1rem auto;">
    <main>
        <section>
            <!--LE LOGO EST TEMPORAIRE, LE TEMPS DE CHARGER L'OFFICIEL SUR UN SERVEUR-->
            <a href="http://www.celiarouby-sophrologue.fr" id="logo" ><img src="../img/logo-sophro-v03.png" alt="celia-rouby-sophrologue"></a><br>
            <h2 style="font-size: 2rem; font-weight: bold; color: #7ECBD6;">Bonjour {{ firstName }} {{ lastName }} !</h2>
            <h3>Votre rendez-vous avec <strong>Célia Rouby Sophrologue le {{ jour }} à {{ heure }}</strong> a été annulé.</h3>
            <p>Si vous n'êtes pas à l'origine de cette demande ou si vous n'en avez pas été informé.e au préalable, merci de me contacter :<br>
                <a href="tel:+33673851774">06.73.85.17.74</a><br>
                <a href="mailto:celia.rouby@gmail.com">celia.rouby@gmail.com</a></p>
            <h4>À bientôt!</h4>
        </section>
    </main>
</body>
