<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rendez-Vous annulé avec Célia Rouby - Sophrologue</title>
</head>

<body style="width: 90%; text-align: center; font-family: 'Quicksand', sans-serif; font-size: 1.4rem; line-height: 1.6; margin: 1rem auto;">
    <main>
        <section>
            <h1 style="font-family: 'Handlee', cursive; font-size: 2rem; font-weight: bold; color: #7ECBD6;">Bonjour {{ firstName }} {{ lastName }} !</h1>
            <h2>Votre rendez-vous avec <strong>Célia Rouby Sophrologue le {{ jour }} à {{ heure }}</strong> a été annulé.</h2>
            <p>Si vous n'êtes pas à l'origine de cette demande ou si vous n'en avez pas été informé.e au préalable, merci de me contacter :<br>
                <a href="http://www.celia-rouby-sophrologue.fr" style="font-family: 'Handlee', cursive;">celiarouby-sophrologue.fr</a><br>
                <a href="tel:+33673851774">06.73.85.17.74</a><br>
                <a href="mailto:celia.rouby@gmail.com">celia.rouby@gmail.com</a></p>
            <h3>À bientôt!</h3>
        </section>
    </main>
</body>

</html>