<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email envoyé à Célia Rouby - Sophrologue</title>
</head>

<body style="width: 100%; text-align: center; font-family: 'Quicksand', sans-serif; font-size: 1.4rem; line-height: 1.6; margin: 1rem auto;">
    <main>
        <section>
            <h1 style="font-family: 'Handlee', cursive; font-size: 2rem; font-weight: bold; color: #7ECBD6;">Merci {{ firstName }} {{ lastName }}</h1>
            <p>Votre email a été envoyé avec succès à <a href="mailto:celia.rouby@gmail.com">celia.rouby@gmail.com</a></p>
            <p>Votre message :<br>
                <strong><em>{{ message }}</em></strong></p>
            <a href="http://www.celia-rouby-sophrologue.fr" style="font-family: 'Handlee', cursive;">celiarouby-sophrologue.fr</a>
        </section>
    </main>
</body>

</html>