<body style="width: 100%; text-align: center; font-family: 'Quicksand', sans-serif; font-size: 1.4rem; line-height: 1.6; margin: 1rem auto;">
    <main>
        <section>
            <h2 style="font-family: 'Handlee', cursive; font-size: 2rem; font-weight: bold; color: #7ECBD6;">Rendez-vous annulé:</h2>
            <p>Vous avez annulé votre rendez-vous avec : <br>
                <strong>{{ firstName }} {{ lastName }}</strong>. <br>
                Le <strong>{{ jour }} à {{ heure }}</strong>.</p>
            <p>{{ email }}<br>
                <a href="tel:{{ phone }}">{{ phone }}</a></p>
        </section>
    </main>
</body>
