<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Message Patient</title>
</head>

<body style="width: 100%; text-align: center; font-family: 'Quicksand', sans-serif; font-size: 1.4rem; line-height: 1.6; margin: 1rem auto;">
    <main>
        <section>
            <h1 style="font-family: 'Handlee', cursive; font-size: 2rem; font-weight: bold; color: #7ECBD6;">Nouveau message de {{ firstName }} {{ lastName }}</h1>
            <p>{{ email }}<br>
                <a href="tel:{{ phone }}">{{ phone }}</a></p>
            <p><strong><em>{{ message }}</em></strong></p>
        </section>
    </main>
</body>

</html>