<body style="width: 100%; text-align: center; font-family: 'Quicksand', sans-serif; font-size: 1.4rem; line-height: 1.6; margin: 1rem auto;">
    <main>
        <section>
            <!--LE LOGO EST TEMPORAIRE, LE TEMPS DE CHARGER L'OFFICIEL SUR UN SERVEUR-->
            <a href="http://www.celiarouby-sophrologue.fr" id="logo" ><img src="../img/logo-sophro-v03.png" alt="celia-rouby-sophrologue"></a><br>
            <h2 style="font-size: 2rem; font-weight: bold; color: #7ECBD6;">Rendez-vous annulé:</h2>
            <p>Vous avez annulé votre rendez-vous avec : <br>
                <strong>{{ firstName }} {{ lastName }}</strong>. <br>
                Le <strong>{{ jour }} à {{ heure }}</strong>.</p>
            <p>{{ email }}<br>
                <a href="tel:{{ phone }}">{{ phone }}</a></p>
        </section>
    </main>
</body>
