<section id="applications">
  <section id="indications">
    <h1 class="mainTitle">Les Domaines d'Application</h1>
      <div id="application1">
          <article id="da1" class="domaines">
              <h2>AMÉLIORATION DU QUOTIDIEN</h2>
              <div>
                  <i class="fas fa-sun"></i>
                  <ul>
                      <li>Gérer son stress, son anxiété ·</li>
                      <li>Mieux vivre ses émotions ·</li>
                      <li>Mieux vivre son hypersensibilité ·</li>
                      <li>Lâcher-prise, prendre du recul ·</li>
                      <li>Se détendre, apprendre à se relaxer ·</li>
                      <li>Améliorer la qualité de son sommeil ·</li>
                      <li>S’adapter au changement (nouvel emploi, naissance, retraite…) ·</li>
                      <li>Traverser une épreuve (divorce, deuil, maladie…) ·</li>
                      <li>Gérer la charge mentale ·</li>
                      <li>Améliorer ses relations ·</li>
                      <li>Prévenir ou accompagner le burnout ·</li>
                      <li>Retrouver du sens à sa vie, à son travail ·</li>
                      <li>Développer sa spiritualité ·</li>
                  </ul>
              </div>
          </article>
          <article id="da2" class="domaines">
              <h2>DÉVELOPPEMENT DU POTENTIEL</h2>
              <div>
                  <i class="fas fa-smile-beam"></i>
                  <ul>
                      <li>· Concentration</li>
                      <li>· Calme</li>
                      <li>· Mémoire</li>
                      <li>· Créativité</li>
                      <li>· Intuition</li>
                      <li>· Estime de soi</li>
                      <li>· Confiance en soi</li>
                      <li>· Affirmation de soi</li>
                      <li>· Parler en public</li>
                  </ul>
              </div>
          </article>
      </div>
      <div id="application2">
          <article id="da3" class="domaines">
              <h2>PRÉPARATION MENTALE</h2>
              <div>
                  <i class="far fa-user"></i>
                  <i class="fas fa-cogs"></i>
                 <!-- <i class="fas fa-users"></i>-->
                  <ul>
                      <li><h4>POUR TOU·TE·S :</h4></li>
                      <li>Grossesse & Parentalité ·</li>
                      <li>Coming out ·</li>
                      <li>Permis de conduire ·</li>
                      <li>Entretien professionnel ·</li>
                      <li>Prise de parole en public ·</li>
                      <li><h4>POUR SPORTIF·VE·S :</h4></li>
                      <li>Préparation à la compétition ·</li>
                      <li>Gestion du stress & des émotions ·</li>
                      <li>Renforcement de la motivation ·</li>
                      <li>Confiance en soi ·</li>
                      <li><h4>POUR LYCÉEN·NE·S ET ÉTUDIANT·E·S :</h4></li>
                      <li>Préparation aux examens & concours ·</li>
                      <li>(gestion du stress, mémoire, concentration, confiance en soi…)</li>
                  </ul>
              </div>
          </article>
          <article id="da4" class="domaines">
              <h2>ACCOMPAGNEMENT THÉRAPEUTIQUE</h2>
              <div>
                  <i class="fas fa-comment-medical"></i>
                  <ul>
                      <li>· Gestion de la douleur (migraines, endométriose, fibromyalgie…)</li>
                      <li>· Accompagnement d’un traitement médical</li>
                      <li>· Accompagnement du cancer</li>
                      <li>· Acouphènes, hyperacousie, misophonie</li>
                      <li>· Troubles alimentaires (anorexie, boulimie)</li>
                      <li>· Addictions, pulsions</li>
                      <li>· Préparation à une intervention chirurgicale</li>
                      <li>· Troubles sexuels</li>
                  </ul>
              </div>
          </article>
      </div>
      <p class="italic">La sophrologie est une technique de support qui <span class="bold blue">ne se substitue en aucun cas à un avis et/ou traitement médical</span>. Seul le médecin est habilité à diagnostiquer et prescrire.</p>
  </section>
    <section id="accomp">
      <article>
          <article class="accomp" id="accompIndiv">
              <h3>ACCOMPAGNEMENT INDIVIDUEL</h3>
              <div class="accompDesc" id="accompIndivDesc">
                  <i class="fas fa-user"></i>
                      <ul>
                          <li>Un accompagnement personnalisé et adapté à vos besoins.</li>
                          <li>Entre 8 et 12 séances selon votre objectif.</li>
                          <li>Séances hebdomadaires d'1h (sauf la première qui dure 1h30 afin de vous laisser le temps
                              d’exposer vos besoins et votre objectif).
                          </li>
                          <li>J’accompagne adultes et adolescents.</li>
                      </ul>
              </div>
              <article class="accompSeance" id="accompIndivSeance">
                  <h4>DÉROULÉ D’UNE SÉANCE :</h4>
                  <ul>
                      <li>Temps d’échange pour vous exprimer (et clarifier votre objectif durant la première séance)</li>
                      <li>Pratique d’exercices de relaxation dynamique : des mouvements simples et doux synchronisés sur la respiration avec concentration sur vos ressentis corporels</li>
                      <li>Pratique d’une visualisation positive pour prolonger la détente et explorer ses ressources</li>
                      <li>Temps d’expression des ressentis</li>
                  </ul>
              </article>
          </article>
          <a href="prendre-rdv.php" class="button">Prendre RDV</a>
      </article>
      <article>
          <article class="accomp" id="accompColl">
              <h3>SÉANCES COLLECTIVES</h3>
              <div class="accompDesc" id="accompCollDesc">
                  <i class="fas fa-user-friends"></i>
                      <ul>
                          <li>Séances collectives sur un thème commun et accessibles à tou·te·s (relaxation, détente).</li>
                          <li>Séances entièrement dédiées à la pratique de la sophrologie, pour la découvrir ou la pratiquer
                              régulièrement à moindre coût.
                          </li>
                          <li>Séances hebdomadaires sans engagement d'1h.</li>
                      </ul>
              </div>
              <article class="accompSeance" id="accompCollSeance">
                  <h4>DÉROULÉ D’UNE SÉANCE :</h4>
                  <ul>
                      <li>Temps d’échange pour vous exprimer</li>
                      <li>Pratique d’exercices de relaxation dynamique afin de vous détendre</li>
                      <li>Pratique d’une visualisation positive pour prolonger la détente et explorer ses ressources</li>
                      <li>Temps d’expression des ressentis</li>
                  </ul>
              </article>
          </article>
          <a href="contact.php">S'inscrire</a>
      </article>
      <article>
          <article class="accomp" id="accompInstit">
              <h3>EN ENTREPRISE, EN LYCÉE, EN ASSOCIATION…</h3>
              <div class="accompDesc" id="accompInstitDesc">
                  <i class="fas fa-users"></i>
                      <ul>
                          <li>Pour une pratique en groupe, portée par un objectif commun.</li>
                          <li>Eentre 8 et 12 séances selon votre objectif.</li>
                          <li>Séances hebdomadaires d'1h.</li>
                      </ul>
              </div>
              <article class="accompSeance" id="accompInstitSeance">
                  <h4>DÉROULÉ D’UNE SÉANCE :</h4>
                  <ul>
                      <li>Temps d’échange pour vous exprimer</li>
                      <li>Pratique d’exercices de relaxation dynamique : des mouvements simples et doux synchronisés sur la
                          respiration
                      </li>
                      <li>avec concentration sur vos ressentis corporels</li>
                      <li>Pratique d’une visualisation positive pour prolonger la détente et explorer ses ressources</li>
                      <li>Temps d’expression des ressentis</li>
                  </ul>
              </article>
          </article>
      </article>
    </section>
    <section>
        <article id="institDetails">
            <article class="institDetails" id="institDetailsComp">
                <h3>EN ENTREPRISE</h3>
                <i class="fas fa-briefcase"></i>
                <ul>
                    <li>Gestion du stress</li>
                    <li>Cohésion et travail en équipe</li>
                    <li>Amélioration des performances</li>
                    <li>Concentration</li>
                    <li>Booster la créativité</li>
                    <li>Adaptation aux changements</li>
                    <li>Prise de parole en public</li>
                    <li>Bien être au travail</li>
                    <li>etc…</li>
                </ul>
            </article>
            <article class="institDetails" id="institDetailsSchool">
                <h3>AU LYCÉE, EN ÉCOLE</h3>
                <i class="fas fa-user-graduate"></i>
                <ul>
                    <li>Gestion du stress</li>
                    <li>Gestion des émotions</li>
                    <li>Motivation</li>
                    <li>Concentration</li>
                    <li>Confiance en soi</li>
                    <li>Renforcer ses capacités</li>
                    <li>Relations avec les autres</li>
                    <li>Préparation aux examens</li>
                    <li>etc…</li>
                </ul>
            </article>
            <article class="institDetails" id="institDetailsRet">
                <h3>EN MAISON DE RETRAITE</h3>
                <i class="fas fa-clinic-medical"></i>
                <ul>
                    <li>Gestion des angoisses</li>
                    <li>Gestion des douleurs</li>
                    <li>Troubles du sommeil</li>
                    <li>Entretenir sa mémoire</li>
                    <li>Entretenir sa mobilité</li>
                    <li>Détente physique</li>
                    <li>Détente psychologique</li>
                    <li>Adaptation à cette nouvelle vie</li>
                    <li>etc…</li>
                </ul>
            </article>
            <article class="institDetails" id="institDetailsSport">
                <h3>EN CLUB SPORTIF</h3>
                <i class="fas fa-running"></i>
                <ul>
                    <li>Gestion du stress</li>
                    <li>Concentration</li>
                    <li>Motivation</li>
                    <li>Préparation mentale</li>
                    <li>Confiance en soi</li>
                    <li>Cohésion de groupe</li>
                    <li>Récupération mentale et physique</li>
                    <li>etc…</li>
                </ul>
            </article>
        </article>
        <a href="contact.php">Demander un devis</a>
    </section>
</section>
<script type="text/javascript" src="js/active.js"></script>
