<h1 class="mainTitle">Célia Rouby vous accueille dans son Cabinet de Sophrologie à Lyon.</h1>
<section id="homePage">
  <article class="homePage" id="topArticle">
      <h2>Je reçois toute personne pour des problématiques de :</h2>
      <ul id="indexList">
          <li>Stress, burnout, anxiété, ruminations, charge mentale</li>
          <li>Troubles du sommeil, insomnies</li>
          <li>Confiance en soi, estime de soi</li>
          <li>Émotions, colère, jalousie, tristesse</li>
          <li>Difficultés relationnelles</li>
          <li>Concentration, attention, mémoire</li>
          <li>Procrastination, blocages, comportements limitants</li>
          <li>Recherche de sens, recherche identitaire, crise existentielle</li>
          <li>Traumatismes</li>
      </ul>
      <ul id="indexBtns">
          <li><a href="contact.php">Me contacter</a></li>
          <li><a href="prendre-rdv.php">Prendre rendez-vous</a></li>
      </ul>
  </article>
</section>
<script type="text/javascript" src="js/active.js"></script>