<section id="ipPage">
  <h1 class="mainTitle">Infos Pratiques</h1>
  <article id="tarifs">
    <h2>LES TARIFS</h2>
      <ul>
          <li>Séance individuelle (1h) : <span class="bold blue"> 70 €</span></li>
          <li>1ère séance individuelle (1h30) : <span class="bold blue"> 70 €</span></li>
          <li>Séance de groupe : <span class="bold blue"> de 10 à 20 €</span></li>
      </ul>
      <div>
          <p>Séances en entreprise, écoles, etc : <a href="contact.php">sur devis</a>.</p>
          <p>Tarifs adaptés pour les personnes en difficulté financière : <a href="contact.php">me contacter</a>.</p>
      </div>
      <h3>Paiements</h3>
      <p>Moyens de paiement acceptés : <span class="bold"> espèces, chèque</span>.</p>
      <p>Les séances ne sont pas remboursées par la sécurité sociale, mais <span class="bold blue">peuvent être prises en charge par certaines
              mutuelles</span>.</p>
      <p> Renseignez-vous auprès de votre mutuelle.</p>
      <p> Liste des mutuelles disponible
          <a href="www.chambre-syndicale-sophrologie.fr/mutuelle-sophrologie-sophrologue">ici</a>.</p>
  </article>
  <article id="seances">
    <h2>LES SÉANCES</h2>
      <article>
          <h3>Durée d'un accompagnement</h3>
          <ul>
              <li>L'accompagnement individuel en sophrologie varie <span class="bold blue">entre 8 et 12 séances</span>, selon votre
                  objectif.
              </li>
              <li>Les séances sont <span class="bold blue">accessibles à tou·te·s.</span></li>
              <li>La sophrologie se pratique assis·e et/ou debout.</li>
              <li>Il n’est pas exigé de tenue vestimentaire particulière.</li>
          </ul>
      </article>
      <article>
          <h3>Durée d'une séance</h3>
          <ul>
              <li>Séances individuelles et collectives : <span class="bold blue">1h</span></li>
              <li>Première séance individuelle : <span class="bold blue">1h30 environ</span></li>
          </ul>
      </article>
  </article>
  <article id="cabinet">
    <h2>LE CABINET</h2>
      <h3>Plan d'accès</h3>
    <p>25 rue Charles Richard 69003 Lyon</p>
      <p class="bold blue">Les séances peuvent aussi s'effectuer à domicile sur demande.</p>
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11135.747549071975!2d4.8812322!3d45.7524112!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47f4c1c61aebd211%3A0x24611798aabf41d!2s25%20Rue%20Charles%20Richard%2C%2069003%20Lyon!5e0!3m2!1sfr!2sfr!4v1579515801776!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
  </article>
</section>
<script type="text/javascript" src="js/active.js"></script>